### ISSUE TITLE
WireFrame design

### ISSUE THREAD

**Issue by HellHunterMax** [Code2Gether-Discord/JokesOnYou#6]
# Tasks:
- [ ] Navigation Bar
- [ ] Login form
- [ ] Register form
- [ ] Create/Edit/Delete jokes form
- [ ] Admin page for registered user
- [ ] view joke
- [ ] view list of jokes (with category and filters)
- [ ] about us page

#more info:
This can be worked on by multiple people each creating their own page for the Wireframe.
use [Draw.io](http://Draw.io) to create a diagram.

#How To:
https://careerfoundry.com/en/blog/ux-design/free-wireframing-tools/
If someone already started and created a separate branch pull that. See what they made and add to it.
Make a new branch Copied from dev. When finished create pull Request.
Upload all  info to : `Documentation/WireFrame/`
